import { describe,expect,it,vi } from 'vitest';
import {
 ApprovedCalibratedSynchronizationMappingPolicy,auditCalibratedSynchronizationReadiness,
 readCalibratedSynchronizationActivation
} from '../src/subtitles/synchronization-activation.js';
import { createStagingSynchronizationComposition } from '../src/subtitles/synchronization-staging-composition.js';
import type { SynchronizationResult } from '../src/subtitles/synchronization-context.js';
const staging={INDOSYNC_RUNTIME_ENV:'staging',INDOSYNC_CALIBRATED_SYNCHRONIZATION:'true',INDOSYNC_CALIBRATED_TARGET:'staging',INDOSYNC_SYNCHRONIZATION_NAMESPACE:'indosync-sync-staging-test',INDOSYNC_REDIS_CREDENTIAL_ENV:'staging',KV_REST_API_URL:'https://redis.example',KV_REST_API_TOKEN:'token',INDOSYNC_EVIDENCE_ENGINE_COMMAND:process.execPath};
const deps={provider:{name:'fixture',search:vi.fn(),download:vi.fn()},mediaProbe:{probe:vi.fn()},audioExtractor:{extract:vi.fn()}};
function approved():SynchronizationResult{const e=[0,1,2,3].map(i=>({source:{cueIndex:i,startMs:i*1000,endMs:i*1000+900},reference:{startMs:i*1000+100,endMs:i*1000+1000},sourceAnchorMs:i*1000+500,referenceAnchorMs:i*1000+600,confidence:.8,method:'x'}));return{taskId:'t',points:e.map(x=>({sourceMs:x.sourceAnchorMs,referenceMs:x.referenceAnchorMs})),provenance:{kind:'calibrated-model-selection',state:'approved',policyId:'p',policyVersion:'v',modelSelectionVersion:'m'},evidence:e,approvedMapping:{acceptanceStatus:'approved',model:'offset-only',scale:1,offsetMs:100,meanAbsoluteResidualMs:20,inlierRatio:1,temporalCoverage:.8,inlierCount:4,evidenceCount:4,policyId:'p',policyVersion:'v',modelSelectionVersion:'m'},confidence:.8,method:'x',createdAt:1,expiresAt:100};}
describe('calibrated synchronization activation readiness',()=>{
 it.each([undefined,'','false'])('defaults absent/false flag %s to disabled',async flag=>{const env:any={INDOSYNC_RUNTIME_ENV:'staging'};if(flag!==undefined)env.INDOSYNC_CALIBRATED_SYNCHRONIZATION=flag;const c=readCalibratedSynchronizationActivation(env);expect(c).toMatchObject({enabled:false,activation:'disabled'});expect((await auditCalibratedSynchronizationReadiness(c,false)).status).toBe('disabled');expect(await createStagingSynchronizationComposition(env,deps as any)).toBeUndefined();});
 it('fails closed on invalid flag and namespace/credential mismatch',()=>{expect(()=>readCalibratedSynchronizationActivation({...staging,INDOSYNC_CALIBRATED_SYNCHRONIZATION:'yes'})).toThrow();expect(()=>readCalibratedSynchronizationActivation({...staging,INDOSYNC_SYNCHRONIZATION_NAMESPACE:'indosync-sync-production-test'})).toThrow('namespace');expect(()=>readCalibratedSynchronizationActivation({...staging,INDOSYNC_REDIS_CREDENTIAL_ENV:'production'})).toThrow('credential');});
 it('creates staging composition only for explicit staging true and reports ready',async()=>{const x=await createStagingSynchronizationComposition(staging,deps as any);expect(x).toMatchObject({environment:'staging',namespace:'indosync-sync-staging-test',readiness:{status:'ready'}});expect(x?.worker).toBeDefined();expect(x?.runner).toBeDefined();expect(x?.store).toBeDefined();});
 it.each([undefined,'false'])('keeps production %s off',async flag=>{const env:any={...staging,INDOSYNC_RUNTIME_ENV:'production',INDOSYNC_CALIBRATED_TARGET:'production',INDOSYNC_SYNCHRONIZATION_NAMESPACE:'indosync-sync-production-test',INDOSYNC_REDIS_CREDENTIAL_ENV:'production'};if(flag===undefined)delete env.INDOSYNC_CALIBRATED_SYNCHRONIZATION;else env.INDOSYNC_CALIBRATED_SYNCHRONIZATION=flag;expect((await auditCalibratedSynchronizationReadiness(readCalibratedSynchronizationActivation(env),false)).status).toBe('disabled');expect(await createStagingSynchronizationComposition(env,deps as any)).toBeUndefined();});
 it('keeps production with staging target off and incomplete production not ready',async()=>{const mismatch=readCalibratedSynchronizationActivation({...staging,INDOSYNC_RUNTIME_ENV:'production'});expect(mismatch.enabled).toBe(false);expect(await createStagingSynchronizationComposition({...staging,INDOSYNC_RUNTIME_ENV:'production'},deps as any)).toBeUndefined();const incomplete=readCalibratedSynchronizationActivation({...staging,KV_REST_API_URL:'',INDOSYNC_EVIDENCE_ENGINE_COMMAND:''});expect((await auditCalibratedSynchronizationReadiness(incomplete,false)).status).toBe('not_ready');});
 it('approved-only policy rejects legacy, accepted, and rejected results',()=>{const policy=new ApprovedCalibratedSynchronizationMappingPolicy();expect(policy.select(approved())).toMatchObject({scale:1,offsetMs:100,pointsUsed:4});const legacy={...approved(),approvedMapping:undefined,evidence:undefined,provenance:{kind:'legacy-estimator',estimatorVersion:'v'} as const,mapping:{scale:2,offsetMs:999,confidence:1,pointsUsed:4}};expect(policy.select(legacy)).toBeUndefined();for(const state of ['accepted','rejected'] as const){const r=approved();r.provenance={...r.provenance as any,state};r.approvedMapping=undefined;expect(policy.select(r)).toBeUndefined();}});
});
